package db

import (
	"RU-Smart-Workspace/ru-smart-api/domain/entities"
	"RU-Smart-Workspace/ru-smart-api/domain/repositories"
	"log"
	"time"
)

type publicationRepository struct {
	db *OracleDB
}

func NewPublicationRepository(db *OracleDB) repositories.PublicationRepository {
	return &publicationRepository{db: db}
}

func (r *publicationRepository) Create(publication *entities.Publication) error {
	query := `
		INSERT INTO EGRAD_PUBLICATIONS (
			STD_CODE,
			THESIS_TITLE, THESIS_TITLE_ENG, PUBLICATION_TYPE,
			ARTICLE1_JOURNAL,ARTICLE1_EJOURNAL,ARTICLE1_TITLE, JOURNAL1_NAME, JOURNAL1_COUNTRY, 
			JOURNAL1_ACCEPTED,JOURNAL1_PUBLISHED, JOURNAL1_VOLUME, JOURNAL1_ISSUE, JOURNAL1_MONTH,
			JOURNAL1_YEAR, JOURNAL1_PAGE_FROM, JOURNAL1_PAGE_TO, JOURNAL1_LEVEL,JOURNAL1_LEVEL_TCI,JOURNAL1_TCI_GROUP, 
			ARTICLE2_JOURNAL,ARTICLE2_EJOURNAL,ARTICLE2_TITLE, JOURNAL2_NAME, JOURNAL2_COUNTRY,
			JOURNAL2_ACCEPTED, JOURNAL2_PUBLISHED, JOURNAL2_VOLUME, JOURNAL2_ISSUE,
			JOURNAL2_MONTH, JOURNAL2_YEAR, JOURNAL2_PAGE_FROM, JOURNAL2_PAGE_TO,
			JOURNAL2_LEVEL, JOURNAL2_LEVEL_TCI, JOURNAL2_TCI_GROUP, 
			CONF_NATIONAL, CONF_INTERNATIONAL, CONF_ARTICLE_TITLE, CONF_NAME,
			CONF_DATE, CONF_ORGANIZER, CONF_LOCATION, CONF_COUNTRY, 
			CONF_ACCEPTED, CONF_PRESENTED, CONF_PAGE_FROM, CONF_PAGE_TO, CONF_LEVEL,
			OTHER_ARTICLE_TITLE, OTHER_SOURCE_ONLINE,OTHER_SOURCE_ONLINE_TITLE, OTHER_SOURCE,OTHER_SOURCE_TITLE,
			CREATED_AT, UPDATED_AT
		) VALUES (
			:STD_CODE,
			:THESIS_TITLE, :THESIS_TITLE_ENG, :PUBLICATION_TYPE,
			:ARTICLE1_JOURNAL, :ARTICLE1_EJOURNAL, :ARTICLE1_TITLE, :JOURNAL1_NAME, :JOURNAL1_COUNTRY, 
			:JOURNAL1_ACCEPTED,:JOURNAL1_PUBLISHED, :JOURNAL1_VOLUME, :JOURNAL1_ISSUE, :JOURNAL1_MONTH,
			:JOURNAL1_YEAR, :JOURNAL1_PAGE_FROM, :JOURNAL1_PAGE_TO, :JOURNAL1_LEVEL,:JOURNAL1_LEVEL_TCI,:JOURNAL1_TCI_GROUP, 
			:ARTICLE2_JOURNAL, :ARTICLE2_EJOURNAL, :ARTICLE2_TITLE, :JOURNAL2_NAME, :JOURNAL2_COUNTRY,
			:JOURNAL2_ACCEPTED, :JOURNAL2_PUBLISHED, :JOURNAL2_VOLUME, :JOURNAL2_ISSUE,
			:JOURNAL2_MONTH, :JOURNAL2_YEAR, :JOURNAL2_PAGE_FROM, :JOURNAL2_PAGE_TO,
			:JOURNAL2_LEVEL, :JOURNAL2_LEVEL_TCI, :JOURNAL2_TCI_GROUP, 
			:CONF_NATIONAL, :CONF_INTERNATIONAL, :CONF_ARTICLE_TITLE, :CONF_NAME,
			:CONF_DATE, :CONF_ORGANIZER, :CONF_LOCATION, :CONF_COUNTRY, 
			:CONF_ACCEPTED, :CONF_PRESENTED, :CONF_PAGE_FROM, :CONF_PAGE_TO, :CONF_LEVEL,
			:OTHER_ARTICLE_TITLE, :OTHER_SOURCE_ONLINE, :OTHER_SOURCE_ONLINE_TITLE, :OTHER_SOURCE, :OTHER_SOURCE_TITLE,
			:CREATED_AT, :UPDATED_AT
		)
	`

	publication.CreatedAt = time.Now()
	publication.UpdatedAt = time.Now()

	_, err := r.db.GetDB().NamedExec(query, publication)
	return err
}

func (r *publicationRepository) GetByID(id string) (*entities.Publication, error) {
	var publication entities.Publication
	query := `SELECT * FROM egrad_publications WHERE stD_code = :1`

	err := r.db.GetDB().Get(&publication, query, id)
	if err != nil {
		return nil, err
	}

	return &publication, nil
}

func (r *publicationRepository) Update(publication *entities.Publication) error {

	query := `
		UPDATE EGRAD_PUBLICATIONS SET
			THESIS_TITLE = :THESIS_TITLE,
			THESIS_TITLE_ENG = :THESIS_TITLE_ENG,
			PUBLICATION_TYPE = :PUBLICATION_TYPE,
			ARTICLE1_JOURNAL = :ARTICLE1_JOURNAL,
			ARTICLE1_EJOURNAL = :ARTICLE1_EJOURNAL,
			ARTICLE1_TITLE = :ARTICLE1_TITLE,
			JOURNAL1_NAME = :JOURNAL1_NAME,
			JOURNAL1_COUNTRY = :JOURNAL1_COUNTRY,
			JOURNAL1_ACCEPTED = :JOURNAL1_ACCEPTED,
			JOURNAL1_PUBLISHED = :JOURNAL1_PUBLISHED,
			JOURNAL1_VOLUME = :JOURNAL1_VOLUME,
			JOURNAL1_ISSUE = :JOURNAL1_ISSUE,
			JOURNAL1_MONTH = :JOURNAL1_MONTH,
			JOURNAL1_YEAR = :JOURNAL1_YEAR,
			JOURNAL1_PAGE_FROM = :JOURNAL1_PAGE_FROM,
			JOURNAL1_PAGE_TO = :JOURNAL1_PAGE_TO,
			JOURNAL1_LEVEL = :JOURNAL1_LEVEL,
			JOURNAL1_LEVEL_TCI = :JOURNAL1_LEVEL_TCI,
			JOURNAL1_TCI_GROUP = :JOURNAL1_TCI_GROUP,
			ARTICLE2_TITLE = :ARTICLE2_TITLE,
			JOURNAL2_NAME = :JOURNAL2_NAME,
			JOURNAL2_COUNTRY = :JOURNAL2_COUNTRY,
			JOURNAL2_ACCEPTED = :JOURNAL2_ACCEPTED,
			JOURNAL2_PUBLISHED = :JOURNAL2_PUBLISHED,
			JOURNAL2_VOLUME = :JOURNAL2_VOLUME,
			JOURNAL2_ISSUE = :JOURNAL2_ISSUE,
			JOURNAL2_MONTH = :JOURNAL2_MONTH,
			JOURNAL2_YEAR = :JOURNAL2_YEAR,
			JOURNAL2_PAGE_FROM = :JOURNAL2_PAGE_FROM,
			JOURNAL2_PAGE_TO = :JOURNAL2_PAGE_TO,
			JOURNAL2_LEVEL = :JOURNAL2_LEVEL,
			JOURNAL2_LEVEL_TCI = :JOURNAL2_LEVEL_TCI,
			JOURNAL2_TCI_GROUP = :JOURNAL2_TCI_GROUP,
			CONF_NATIONAL = :CONF_NATIONAL, 
			CONF_INTERNATIONAL = :CONF_INTERNATIONAL,
			CONF_ARTICLE_TITLE = :CONF_ARTICLE_TITLE,
			CONF_NAME = :CONF_NAME,
			CONF_DATE = :CONF_DATE,
			CONF_ORGANIZER = :CONF_ORGANIZER,
			CONF_LOCATION = :CONF_LOCATION,
			CONF_COUNTRY = :CONF_COUNTRY,
			CONF_ACCEPTED = :CONF_ACCEPTED,
			CONF_PRESENTED = :CONF_PRESENTED,
			CONF_PAGE_FROM = :CONF_PAGE_FROM,
			CONF_PAGE_TO = :CONF_PAGE_TO,
			CONF_LEVEL = :CONF_LEVEL,
			OTHER_ARTICLE_TITLE = :OTHER_ARTICLE_TITLE,
			OTHER_SOURCE_ONLINE = :OTHER_SOURCE_ONLINE,
			OTHER_SOURCE_ONLINE_TITLE = :OTHER_SOURCE_ONLINE_TITLE,
			OTHER_SOURCE = :OTHER_SOURCE,
			OTHER_SOURCE_TITLE = :OTHER_SOURCE_TITLE,
			UPDATED_AT = :UPDATED_AT
		WHERE STD_CODE = :STD_CODE
	`

	publication.UpdatedAt = time.Now()
	_, err := r.db.GetDB().NamedExec(query, publication)
	return err
}

func (r *publicationRepository) Delete(studentID string) error {
	query := `DELETE FROM egrad_publications WHERE STD_CODE = :1`
	_, err := r.db.GetDB().Exec(query, studentID)
	return err
}

func (r *publicationRepository) List(offset, limit int) ([]*entities.Publication, error) {
	var publications []*entities.Publication
	query := `SELECT * FROM egrad_publications ORDER BY CREATED_AT DESC OFFSET :1 ROWS FETCH NEXT :2 ROWS ONLY`
	log.Print(offset, limit)
	err := r.db.GetDB().Select(&publications, query, offset, limit)
	return publications, err
}

func (r *publicationRepository) GetByStudentID(studentID string) ([]*entities.Publication, error) {
	var publications []*entities.Publication
	query := `SELECT * FROM egrad_publications WHERE STD_CODE = :1 ORDER BY CREATED_AT DESC`

	err := r.db.GetDB().Select(&publications, query, studentID)
	return publications, err
}
